stages:
  - publish
  - deploy

variables:
  API_TAG_LATEST: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

publish:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  before_script:
    - mkdir -p $HOME/.docker
    - echo "$DOCKER_AUTH_CONFIG" > $HOME/.docker/config.json
  script:
    - docker build -t $API_TAG_LATEST -f ./docker/files/prod.Dockerfile --target production  .
    - docker push $API_TAG_LATEST
  only:
    - tags

deploy:
  image: alpine:latest
  stage: deploy
  when: manual
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
    - eval $(ssh-agent -s)
    - echo "$PRIVATE_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - scp $APP_ENV $SERVER_USER@$SERVER_IP:/docker-deployments/env/api.env
    - ssh $SERVER_USER@$SERVER_IP "cd /docker-deployments && make deploy tag=$CI_COMMIT_TAG"
  environment:
    name: staging
    url: http://159.89.207.22
  only:
    - tags